version: '3.8'

services:
  nginx:
    container_name: laravel7_nginx
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./_docker/nginx/log:/var/log/nginx
    working_dir: /var/www
    restart: unless-stopped
    networks:
      - laravel7_network
  app:
    container_name: laravel7_app
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - laravel7_network

networks:
  laravel7_network:
    driver: bridge